create table if not exists voters (
    id bigint generated by default as identity primary key,
    full_name varchar(255) not null,
    passport_id varchar(255) not null,
    district varchar(255) not null,
    password_hash varchar(255) not null,
    is_voted boolean not null,
    created_at timestamp not null,
    constraint uk_voter_passport_id unique (passport_id)
);

create table if not exists candidates (
    id bigint generated by default as identity primary key,
    full_name varchar(255) not null,
    party varchar(255) not null,
    district varchar(255) not null,
    photo_url varchar(512),
    photo_version bigint not null default 1,
    vote_count integer not null
);

create table if not exists votes (
    id bigint generated by default as identity primary key,
    voter_id bigint not null,
    candidate_id bigint not null,
    created_at timestamp not null,
    constraint uk_vote_voter unique (voter_id),
    constraint fk_vote_voter foreign key (voter_id) references voters (id),
    constraint fk_vote_candidate foreign key (candidate_id) references candidates (id)
);
